baseURL = "https://swayam-gupta.netlify.app/"
languageCode = "en-us"
title = "Swayam Gupta"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

[params]
title = "Swayam Gupta"
description = "Text about me"
favicon = "/images/Profile/me.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Swayam Gupta"
  disableSearch = false
  enableSeparator = false

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Swayam."
  subtitle = "I craft innovative solutions for the digital world"
  content = "A passionate web and app developer skilled in JavaScript, SvelteKit, React, and Java. I create user-focused, dynamic applications and AI-driven platforms, delivering impactful and modern digital solutions."
  image = "/images/Profile/ProfilePhoto.png"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = true
    name = "Resume"
    url = "/Resume/Swayam Gupta.pdf"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fas fa-envelope"
url = "mailto:swayamgupta5698@gmail.com"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/SleepyMiner"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "www.linkedin.com/in/swayam-gupta-830ab227b"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-instagram"
url = "https://www.instagram.com/_swayam_gupta___/"

  [params.about]
  enable = true
  title = "About Me"
  image = "/images/Profile/me.png"
  content = """

I am a software developer with a passion for crafting innovative web and app solutions. With a background in computer science and hands-on experience in cybersecurity, I am deeply interested in the synergy of technology, creativity, and problem-solving. 

My work focuses on building impactful, user-focused systems that bridge gaps and drive meaningful outcomes."""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = [ "SvelteKit", "TailwindCSS", "JavaScript", "React", "C++", "Java" ]

  [params.experience]
  enable = true

   [[params.experience.items]]
    job = "Club Leader"
    company = "Amity University"
    companyUrl = "https://amity.edu/ranchi/"
    date = "Sep 2024 - Present"
    content = """
I am currently working as a Club Leader of Innovate Explore of AIIT at Amity University Jharkhand, Ranchi. I aim to foster a culture of creativity, learning, and collaboration among students. The club serves as a platform for exploring new technologies, developing innovative solutions, and promoting interdisciplinary knowledge sharing to solve real-world problems.

- Define the club’s vision, set goals, and outline strategies to engage and inspire members effectively.
- Oversee club initiatives, ensuring projects are well-planned, executed, and aligned with the club's objectives.
- Organize hands-on workshops, hackathons, and brainstorming sessions to encourage skill development and creative thinking.
- Guide members in their projects and promote teamwork by fostering a collaborative environment.
"""

      [params.experience.items.info]
      enable = true

      [params.experience.items.featuredLink]
      enable = true
      url = "https://amity.edu/ranchi/"

    [[params.experience.items]]
    job = "Summer Intern"
    company = "SAP"
    companyUrl = "https://www.sap.com"
    date = "Jul 2024 - Aug 2024"
    content = "I worked as a software developer intern at [SAP Labs India](https://www.sap.com/india/about/labs-india.html) in Bengaluru. During my internship, I contributed to projects focused on optimizing demand analysis and dealer allocation, creating dynamic web applications to support the automotive industry."

    [params.experience.items.info]
      enable = true
      content = "I worked as a summer intern for two months."

    [[params.experience.items]]
    job = "Full Stack Web Development Intern"
    company = "Bharat Intern"
    companyUrl = "https://bharatintern.live/"
    date = "Feb 2024 - Mar 2024"
    content = """
I worked as a full stack web developer intern at [Bharat Intern](https://bharatintern.live/). I complete a lot of projects while working as an intern. Some of them are listed below:

- [Blog Website](https://github.com/SleepyMiner/Bharat-Intern/tree/main/Blog-Website) : A blog website where users can create, edit, and publish blog posts. It includes features for formatting text, adding images, and displaying posts in a user-friendly manner.
- [Money Tracker](https://github.com/SleepyMiner/Bharat-Intern/tree/main/Money_Tracker) : This project allows users to input their income and expenses, categorize transactions, and generate summaries or reports to help manage their finances.
- [Registration Form](https://github.com/SleepyMiner/Bharat-Intern/tree/main/Registration-Form) : This project includes fields for collecting user information such as name, email, and password, with validation to ensure data accuracy and secure submission for account creation.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://github.com/SleepyMiner/Bharat-Intern"

      [params.experience.items.info]
      enable = true
      content = "I worked as an intern for one month."


  [params.education]
  enable = true
  index = false

    [[params.education.items]]
    title = "Bachelor of Computer Applications"
    date = "2022 - 2025"
    GPA = "8.53 out of 10.0"
    content = """
Extracurricular Activities
  - Acquired 1st Position in Internal Smart India Hackathon 2023
  - Selected and Secured 5th Position for National level Innovathon (Hackathon) organised by Amity University
Gurugram, Haryana
  - Have been Event Coordinator of ’Rangotsav’ event of AIIT and SWD 2024
  - Have been Event Coordinator of 'Spooky Tales' event of AIIT 2024
  - Acquired 2nd Position in 3 Day IIC Hackathon under AUJ
  - Acquired 1st Position in Innovision , Amiphoria 2024"""

      [params.education.items.school]
      name = "Amity University Jharkhand, Ranchi"
      url = "https://amity.edu/ranchi/"

    
    [[params.education.items]]
    title = "Higher Secondary"
    GPA = "8.20 out of 10.0"

      [params.education.items.school]
      name = "B.S.K College, Maithon"
      url = "https://www.bskcollege.ac.in/"
    
    [[params.education.items]]
    title = "Secondary School"
    GPA = "8.10 out of 10.0"

      [params.education.items.school]
      name = "D.A.V Public School, Rupnarainpur"
      url = "https://davpshclrupnarainpur.org/"

  [params.achievements]
  enable = true

    [[params.achievements.items]]
    title = "Internal SIH Winner 2024"
    content = "Our team presented a innovative solution to the problem statement and won."
    url = "https://www.linkedin.com/posts/dr-ashok-k-srivastava-19a5716b_hackathon-sih2023-innovation-ugcPost-7111261731737264128-ZCNr?utm_source=share&utm_medium=member_desktop"
    image = "/images/Achievements/SIH 2023.jpg"

    [[params.achievements.items]]
    title = "Winner of Innovision 2024"
    content = "I led the team as a team leader and with my leadership we presented and won."

    [[params.achievements.items]]
    title = "2nd Position in 3 Day IIC Hackathon"
    content = "We as a team coded and presented in the hackathon and we came second in the competition."

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Image Server"
    content = "PhotoCloud is a modern, lightweight application built using SvelteKit and PocketBase. It allows users to upload, manage, and search for images."
    image = "/images/Project/ImageServer.png"
    badges = [ "SvelteKit", "PocketBase", "Bun", "TypeScript" ]

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/SleepyMiner/ImageServer"

    [[params.projects.items]]
    title = "Career Cove"
    content = "Internship and Job Platform for SIH 2024 Problem Statement"
    image = "/images/Project/Career Cove.png"
    badges = [ "Spring Boot", "React", "TailwindCSS", "TypeScript" ]

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/SleepyMiner/SIH1632"

    [[params.projects.items]]
    title = "Portfolio Website"
    content = "A clean and simple Portfolio website made with React"
    image = "/images/Project/Portfolio Website.png"
    badges = [ "ReactJS", "TailwindCSS", "TailwindCSS" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://swayam-gupta.vercel.app/"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/SleepyMiner/portfolioWebsite"

    [[params.projects.items]]
    title = "Discord Bot"
    content = "A easy to use discord bot which offers many features."
    image = "/images/Project/Discord Bot.jpeg"
    badges = [ "JavaScript", "DiscordJS" ]

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/SleepyMiner/Discord-JS"

  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  btnName = "Mail me"
  btnLink = "mailto:swayamgupta5698@gmail.com"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/SleepyMiner"
linkedin = "www.linkedin.com/in/swayam-gupta-830ab227b"
instagram = "https://www.instagram.com/_swayam_gupta___/"

  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]
  socialShare = true

    [params.singlePages.readTime]
    enable = true
    content = "min read"

    [params.singlePages.scrollprogress]
    enable = true

    [params.singlePages.tags]
    openInNewTab = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
